### ISSUE TITLE
Change body pose when hold position of foot

### ISSUE THREAD

**Issue by amyt197** [lnotspotl/notspot_sim#3]
Hi, thanks for sharing your project, it helps me a lot. 
I'm in trouble with change body pose without change the position of foot in the gazebo (RestController in your project). I cannot get the idea. Please help me
When I publish angle through rostopic, it changes the position of each leg, not the body. How can I get current position of each foot in gazebo and fix it? I'm beginner in this field!!!
Thank you very much!
P/s: My English is not good, hope you understand :)

**Comment by hariharan382** [comment]
did you find the answer?
